# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*" # modify this to only run on certain branches

jobs:
  test:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix: # runs a test for each item in strategy matrix
    #     node-version: [20.x] # needs to be updated to fit project standard
    #     # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    # env: # uncomment if env vars needed for build step

    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - run: bun install --frozen-lockfile
    - run: bun lint
    - run: bun run build
    # - run: bun test
